name: Prepare Images

on:
  pull_request:
    branches:
      - "main"
      - "release*"

jobs:
  prepare-images:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Kyverno Images were built successfully'
      # - name: Checkout
      #   uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      # - name: Setup caches
      #   uses: ./.github/actions/setup-caches
      #   timeout-minutes: 5
      #   continue-on-error: true
      #   with:
      #     build-cache-key: build-images
      # - name: Setup build env
      #   uses: ./.github/actions/setup-build-env
      #   timeout-minutes: 10
      #   with:
      #     free-disk-space: false
      # - name: ko build
      #   shell: bash
      #   run: |
      #     set -e
      #     VERSION=${{ github.ref_name }} make docker-save-image-all
      # - name: upload images archive
      #   uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
      #   with:
      #     name: kyverno.tar
      #     path: kyverno.tar
      #     retention-days: 1
      #     if-no-files-found: error

  trigger-conformance:
    needs: prepare-images
    name: Trigger Conformance Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Conformance Workflow
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const repo_full_name = context.payload.repository.full_name;
            const [owner, repo] = repo_full_name.split('/');
            const { data: workflows } = await github.rest.actions.listRepoWorkflows({ owner, repo });
            const workflow = workflows.workflows.find(w => w.name === 'Conformance tests');
            await github.rest.actions.createWorkflowDispatch({
              owner,
              repo,
              workflow_id: workflow.id,
              ref: "${{ github.event.pull_request.head.ref }}",
            });

  trigger-load-tests:
    needs: prepare-images
    name: Trigger Load Testing Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Load Testing Workflow
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const repo_full_name = context.payload.repository.full_name;
            const [owner, repo] = repo_full_name.split('/');
            const { data: workflows } = await github.rest.actions.listRepoWorkflows({ owner, repo });
            const workflow = workflows.workflows.find(w => w.name === 'Baseline Load Tests');
            console.log("${{ github.event.pull_request.head.ref }}");
            await github.rest.actions.createWorkflowDispatch({
              owner,
              repo,
              workflow_id: workflow.id,
              ref: "${{ github.event.pull_request.head.ref }}",
            });
